nodeLinker: node-modules

packageExtensions:
  debug-logfmt@*:
    dependencies:
      debug: '*'
  'buffer-equal-constant-time@*':
    dependencies:
      buffer: '*'
  jws@*:
    dependencies:
      jwa: '2.0.0'
