import mongoose from 'mongoose';
import type { Document } from 'mongoose';
import { v4 as uuidv4 } from 'uuid';
import './define-getters';

/**
 * Action offered by an assistant message (e.g. "Choose voice")
 */
export interface IChatMessageAction {
  /** Action type identifier the frontend maps to a handler */
  type: string;
  /** Button label */
  label: string;
  /** Optional params for the action (e.g. set volume) */
  payload?: unknown;
  /** Whether this action has been consumed/completed */
  completed?: boolean;
}

/**
 * Chat message interface
 */
export interface IChatMessage {
  /** Stable ID for per-message acking (not Mongo _id) */
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  agentUsed?: string | null; // Track which agent generated this message
  actions?: IChatMessageAction[];
}

/**
 * Word timing from TTS
 */
export interface IWordTiming {
  word: string;
  start: number;
  end: number;
  confidence: number;
  punctuated_word?: string;
  isVisible?: boolean;
  isParagraphEnd?: boolean;
}

/**
 * Workflow state that persists across messages
 * These fields track the multi-turn video creation flow
 */
export interface IWorkflowState {
  // The video topic being worked on
  requestedTopic?: string;
  // Generated script content
  generatedScript?: string;
  // Whether the script was provided by the user (vs generated by scriptwriter)
  userProvidedScript?: boolean;
  // Whether the user has confirmed the script
  scriptConfirmed?: boolean;
  // User's library IDs for footage search
  libraryIds?: string[];
  // Voice ID for TTS generation
  voiceId?: string;
  // Whether voice selection step has been completed (gate for footage_fetcher)
  voiceSelectionPending?: boolean;
  // Whether a voice change is in progress (user requested a different voice for existing video)
  pendingVoiceChange?: boolean;
  // LLM decision on whether footage is sufficient
  footageDecision?: 'proceed' | 'suggest_alternatives' | '';
  // Status of footage fetching
  footageFetchStatus?: 'pending' | 'found' | 'partial' | 'failed';
  // Created VideoAIData ID after footage fetching
  videoAIDataId?: string;
  // S3 URL for the generated audio
  audioUrl?: string;
  // Transcript with word timings from TTS
  transcriptWithTimings?: IWordTiming[];
  // Explicit language for script generation (e.g. "Spanish", "French")
  scriptLanguage?: string;
}

/**
 * Pending message state for async processing
 * This tracks a message that is currently being processed in the background
 */
export interface IPendingMessage {
  messageId: string; // Unique ID for this pending message
  userMessage: string; // The original user message
  status: 'processing' | 'complete' | 'error';
  currentNode?: string; // Which node is currently processing (for status updates)
  currentStatus?: string; // Human-readable status message
  response: string; // Accumulated response so far
  agentUsed?: string | null;
  error?: string;
  workflowStateUpdates?: Partial<IWorkflowState>; // Updates to apply when complete
  startedAt: Date;
  completedAt?: Date;
}

/**
 * Conversation document interface
 */
export interface IConversation extends Document {
  userId: string;
  title?: string; // Auto-generated from first message
  messages: IChatMessage[];
  workflowState?: IWorkflowState; // Persisted workflow state for multi-turn flows
  pendingMessage?: IPendingMessage; // Currently processing message (for async polling)
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Chat message action sub-schema
 */
const chatMessageActionSchema = new mongoose.Schema<IChatMessageAction>(
  {
    type: { type: String, required: true },
    label: { type: String, required: true },
    payload: { type: mongoose.Schema.Types.Mixed, default: undefined },
    completed: { type: Boolean, default: false }
  },
  { _id: false }
);

/**
 * Chat message sub-schema
 */
const chatMessageSchema = new mongoose.Schema<IChatMessage>(
  {
    id: {
      type: String,
      required: true,
      default: () => uuidv4()
    },
    role: {
      type: String,
      enum: ['user', 'assistant'],
      required: true
    },
    content: {
      type: String,
      required: true
    },
    timestamp: {
      type: Date,
      default: Date.now
    },
    agentUsed: {
      type: String,
      enum: ['scriptwriter', 'script_extractor', 'footage_search', 'footage_fetcher', 'footage_validation', 'video_overlay', 'music_generator', 'orchestrator', 'voice_changer', 'synthesize', null],
      default: null
    },
    actions: {
      type: [chatMessageActionSchema],
      default: undefined
    }
  },
  { _id: false }
);

/**
 * Word timing sub-schema
 */
const wordTimingSchema = new mongoose.Schema<IWordTiming>(
  {
    word: { type: String, required: true },
    start: { type: Number, required: true },
    end: { type: Number, required: true },
    confidence: { type: Number, required: true },
    punctuated_word: { type: String },
    isVisible: { type: Boolean },
    isParagraphEnd: { type: Boolean }
  },
  { _id: false }
);

/**
 * Workflow state sub-schema
 */
const workflowStateSchema = new mongoose.Schema<IWorkflowState>(
  {
    requestedTopic: { type: String, default: '' },
    generatedScript: { type: String, default: '' },
    userProvidedScript: { type: Boolean, default: false },
    scriptConfirmed: { type: Boolean, default: false },
    libraryIds: { type: [String], default: [] },
    voiceId: { type: String, default: 'JBFqnCBsd6RMkjVDRZzb' },
    voiceSelectionPending: { type: Boolean, default: false },
    pendingVoiceChange: { type: Boolean, default: false },
    footageDecision: {
      type: String,
      enum: ['proceed', 'suggest_alternatives', ''],
      default: ''
    },
    footageFetchStatus: {
      type: String,
      enum: ['pending', 'found', 'partial', 'failed'],
      default: 'pending'
    },
    videoAIDataId: { type: String, default: '' },
    audioUrl: { type: String, default: '' },
    transcriptWithTimings: { type: [wordTimingSchema], default: [] },
    scriptLanguage: { type: String, default: '' }
  },
  { _id: false }
);

/**
 * Pending message sub-schema
 */
const pendingMessageSchema = new mongoose.Schema<IPendingMessage>(
  {
    messageId: { type: String, required: true },
    userMessage: { type: String, required: true },
    status: {
      type: String,
      enum: ['processing', 'complete', 'error'],
      default: 'processing'
    },
    currentNode: { type: String },
    currentStatus: { type: String },
    response: { type: String, default: '' },
    agentUsed: { type: String, default: null },
    error: { type: String },
    workflowStateUpdates: { type: mongoose.Schema.Types.Mixed },
    startedAt: { type: Date, default: Date.now },
    completedAt: { type: Date }
  },
  { _id: false }
);

/**
 * Conversation schema
 */
const conversationSchema = new mongoose.Schema<IConversation>(
  {
    userId: {
      type: String,
      required: true,
      index: true
    },
    title: {
      type: String,
      default: null
    },
    messages: {
      type: [chatMessageSchema],
      default: []
    },
    workflowState: {
      type: workflowStateSchema,
      default: () => ({})
    },
    pendingMessage: {
      type: pendingMessageSchema,
      default: null
    },
    isActive: {
      type: Boolean,
      default: true
    }
  },
  {
    timestamps: true
  }
);

// Compound index for efficient queries
conversationSchema.index({ userId: 1, updatedAt: -1 });
conversationSchema.index({ userId: 1, isActive: 1 });

/**
 * Generate title from first user message
 */
conversationSchema.pre('save', function (next) {
  if (!this.title && this.messages.length > 0) {
    const firstUserMessage = this.messages.find(m => m.role === 'user');
    if (firstUserMessage) {
      // Truncate to first 50 chars
      this.title = firstUserMessage.content.substring(0, 50) + (firstUserMessage.content.length > 50 ? '...' : '');
    }
  }
  next();
});

export const Conversation = mongoose.model<IConversation>('Conversation', conversationSchema);
