import { CaptionSettings } from '../types';

export const CAPTION_PRESETS: CaptionSettings[] = [
  {
    type: 'WORD_APPEAR',
    fontFamily: 'Montserrat-Bold',
    name: 'Preset 1',
    isUppercase: true,
    primaryColor: '#ffffff',
    outlineColor: '#000000',
    numberOfLines: 1,
    fontSize: 90,
    verticalFontSize: 120,
    activeWordFontSize: 90,
    verticalActiveWordFontSize: 120,
    maxCharactersPerLine: 40,
    shadow: 1,
    highlightedWordColor: '#ffffff',
    marginV: 15,
    outlineWidth: 2
  },
  {
    type: 'WORD_HIGHLIGHT',
    fontFamily: 'Montserrat-Bold',
    name: 'Preset 2',
    isUppercase: true,
    primaryColor: '#ffffff',
    outlineColor: '#000000',
    numberOfLines: 1,
    fontSize: 90,
    verticalFontSize: 120,
    activeWordFontSize: 90,
    verticalActiveWordFontSize: 120,
    maxCharactersPerLine: 40,
    shadow: 0,
    highlightedWordColor: '#f8e71c',
    marginV: 15,
    outlineWidth: 2
  },
  {
    type: 'WORD_BACKGROUND',
    fontFamily: 'Montserrat-Bold',
    name: 'Preset 3',
    isUppercase: true,
    primaryColor: '#ffffff',
    outlineColor: '#000000',
    backgroundColor: '#9013fe',
    numberOfLines: 1,
    fontSize: 75,
    verticalFontSize: 100,
    activeWordFontSize: 75,
    verticalActiveWordFontSize: 100,
    maxCharactersPerLine: 40,
    shadow: 1,
    highlightedWordColor: '#7ed321',
    marginV: 15,
    outlineWidth: 1
  },
  {
    type: 'WORD_HIGHLIGHT',
    fontFamily: 'Fira Sans Condensed ExtraBold Italic',
    name: 'Preset 4',
    isUppercase: false,
    primaryColor: '#ffffff',
    outlineColor: '#000000',
    backgroundColor: '#9013fe',
    numberOfLines: 1,
    fontSize: 90,
    verticalFontSize: 120,
    activeWordFontSize: 90,
    verticalActiveWordFontSize: 120,
    maxCharactersPerLine: 40,
    shadow: 1,
    highlightedWordColor: '#f8e71c',
    marginV: 15,
    outlineWidth: 1
  },
  {
    type: 'WORD_APPEAR',
    fontFamily: 'Fira Sans Condensed ExtraBold Italic',
    name: 'Preset 5',
    isUppercase: false,
    primaryColor: '#ffffff',
    outlineColor: '#000000',
    backgroundColor: '#9013fe',
    numberOfLines: 1,
    fontSize: 90,
    verticalFontSize: 120,
    activeWordFontSize: 90,
    verticalActiveWordFontSize: 120,
    maxCharactersPerLine: 40,
    shadow: 1,
    highlightedWordColor: '#f8e71c',
    marginV: 15,
    outlineWidth: 1
  },
  {
    type: 'WORD_APPEAR',
    fontFamily: 'Roboto Medium',
    name: 'Preset 6',
    isUppercase: false,
    primaryColor: '#ffffff',
    outlineColor: '#000000',
    backgroundColor: '#9013fe',
    numberOfLines: 1,
    fontSize: 90,
    verticalFontSize: 120,
    activeWordFontSize: 90,
    verticalActiveWordFontSize: 120,
    maxCharactersPerLine: 40,
    shadow: 0,
    highlightedWordColor: '#f8e71c',
    marginV: 15,
    outlineWidth: 1
  }
];
