import { Annotation } from '@langchain/langgraph';
import type { BaseMessage } from '@langchain/core/messages';

/**
 * Chat Orchestrator State
 *
 * Defines the state schema for the chat orchestrator LangGraph.
 * The orchestrator manages conversation flow and routes to specialized sub-agents.
 */
export const ChatState = Annotation.Root({
  // Chat history - accumulates messages throughout the conversation
  messages: Annotation<BaseMessage[]>({
    reducer: (x, y) => x.concat(y),
    default: () => []
  }),

  // MongoDB conversation ID for persistence
  conversationId: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // Firebase user ID
  userId: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // UI context (e.g., editor vs chat page)
  uiContext: Annotation<'chat' | 'editor' | ''>({
    reducer: (x, y) => y ?? x,
    default: () => 'chat'
  }),

  // Current user message being processed
  userMessage: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // Which agent is currently active
  currentAgent: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => 'orchestrator'
  }),

  // Routing decision - which agent to call next
  nextAgent: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // Output from sub-agents (scriptwriter, footage_search, video_overlay)
  agentOutput: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // Which sub-agent was called (for tracking)
  agentUsed: Annotation<string | null>({
    reducer: (x, y) => y ?? x,
    default: () => null
  }),

  // Final response to send to the user
  finalResponse: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // Whether the orchestrator should respond to user (vs delegating)
  shouldRespond: Annotation<boolean>({
    reducer: (x, y) => y ?? x,
    default: () => false
  }),

  // Workflow completion flag
  isComplete: Annotation<boolean>({
    reducer: (x, y) => y ?? x,
    default: () => false
  }),

  // Actions to attach to this turn's assistant message (e.g. voice_select -> "Choose voice")
  responseActions: Annotation<Array<{ type: string; label: string; payload?: unknown; completed?: boolean }>>({
    reducer: (x, y) => y ?? x,
    default: () => []
  }),

  // ===== Footage Validation Fields =====

  // The video topic extracted from user message
  requestedTopic: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // Formatted string of cluster search results from searchClustersByQuery
  clusterSearchResults: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // LLM decision on whether footage is sufficient
  footageDecision: Annotation<'proceed' | 'suggest_alternatives' | ''>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // Alternative topic suggestions based on available clusters
  alternativeSuggestions: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // ===== Script Confirmation & Footage Fetching Fields =====

  // The generated script (stored after scriptwriter runs or extracted from user)
  generatedScript: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // Whether the script was provided by the user (vs generated by scriptwriter)
  // Used to track user-provided scripts that skip footage validation
  userProvidedScript: Annotation<boolean>({
    reducer: (x, y) => y ?? x,
    default: () => false
  }),

  // User's raw script text extracted by orchestrator (before cleaning)
  // This is populated when orchestrator routes to script_extractor
  extractedScriptText: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // Whether the user has confirmed the script
  scriptConfirmed: Annotation<boolean>({
    reducer: (x, y) => y ?? x,
    default: () => false
  }),

  // User's library IDs for footage search
  libraryIds: Annotation<string[]>({
    reducer: (x, y) => y ?? x,
    default: () => []
  }),

  // Voice ID for TTS generation (ElevenLabs voice)
  voiceId: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => 'JBFqnCBsd6RMkjVDRZzb' // Default ElevenLabs voice (George)
  }),

  // Whether voice selection step has been completed (gate for footage_fetcher)
  voiceSelectionPending: Annotation<boolean>({
    reducer: (x, y) => y ?? x,
    default: () => false
  }),

  // Whether a voice change is in progress (user requested new voice for existing video)
  // true = waiting for user to pick a new voice via the selector modal
  pendingVoiceChange: Annotation<boolean>({
    reducer: (x, y) => y ?? x,
    default: () => false
  }),

  // Generated audio file path after TTS
  generatedAudioPath: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // Generated audio file name
  generatedAudioName: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // Transcript with word timings from TTS
  transcriptWithTimings: Annotation<Array<{
    word: string;
    start: number;
    end: number;
    confidence: number;
    punctuated_word?: string;
    isVisible?: boolean;
    isParagraphEnd?: boolean;
  }>>({
    reducer: (x, y) => y ?? x,
    default: () => []
  }),

  // Status of footage fetching
  footageFetchStatus: Annotation<'pending' | 'found' | 'partial' | 'failed'>({
    reducer: (x, y) => y ?? x,
    default: () => 'pending'
  }),

  // Created VideoAIData ID after footage fetching completes
  videoAIDataId: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // S3 URL for the generated audio
  audioUrl: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // ===== Script Language Fields =====

  // Explicit language for script generation (e.g. "Spanish", "French")
  // Set by orchestrator when user requests a specific language for the script
  scriptLanguage: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // ===== Music Generation Fields =====

  // Optional user-provided music style/prompt for background music
  musicStyle: Annotation<string>({
    reducer: (x, y) => y ?? x,
    default: () => ''
  }),

  // ===== Editor Context Fields =====

  // Segment timeline sent from the editor client (only present when uiContext === 'editor').
  // Each entry is a compact { index, timeStart, timeEnd } so the editor command agent can
  // resolve positional references like "first clip" or "last clip" to concrete timestamps.
  segmentContext: Annotation<Array<{ index: number; timeStart: number; timeEnd: number }>>({
    reducer: (x, y) => y ?? x,
    default: () => []
  }),

  // ===== Usage Tracking Fields =====
  // Option A: creditsConsumed removed — all users have unlimited access
});

// Type export for use in nodes and agents
export type ChatStateType = typeof ChatState.State;
