import { GeneratedMusic } from '../models/generated-music';
import { IGeneratedMusic } from '../types';

export class GeneratedMusicRepository {
  /**
   * Create a new generated music record
   */
  async create(musicData: Partial<IGeneratedMusic>): Promise<IGeneratedMusic> {
    const music = new GeneratedMusic(musicData);
    return music.save();
  }

  /**
   * Find music by ID
   */
  async findById(id: string): Promise<IGeneratedMusic | null> {
    return GeneratedMusic.findById(id);
  }

  /**
   * Find music by user ID with pagination
   */
  async findByUserId(userId: string, limit: number = 20, skip: number = 0): Promise<IGeneratedMusic[]> {
    return GeneratedMusic.find({ userId }).sort({ createdAt: -1 }).limit(limit).skip(skip);
  }

  /**
   * Search for existing music by prompt similarity (for reuse)
   */
  async findSimilarMusic(userId: string, prompt: string, limit: number = 5): Promise<IGeneratedMusic[]> {
    // First try exact prompt match
    const exactMatch = await GeneratedMusic.find({ userId, prompt })
      .sort({ usageCount: -1, createdAt: -1 })
      .limit(limit);

    if (exactMatch.length > 0) {
      return exactMatch;
    }

    // Then try text search for similar prompts
    return GeneratedMusic.find(
      {
        userId,
        $text: { $search: prompt }
      },
      { score: { $meta: 'textScore' } }
    )
      .sort({ score: { $meta: 'textScore' }, usageCount: -1 })
      .limit(limit);
  }

  /**
   * Find music by similar characteristics (mood, videoType, etc.)
   */
  async findByCharacteristics(
    userId: string,
    characteristics: {
      estimatedMood?: string;
      videoType?: string;
      duration?: number; // Will find music within ±10% of this duration
    },
    limit: number = 10
  ): Promise<IGeneratedMusic[]> {
    const query: any = { userId };

    if (characteristics.estimatedMood) {
      query.estimatedMood = characteristics.estimatedMood;
    }

    if (characteristics.videoType) {
      query.videoType = characteristics.videoType;
    }

    if (characteristics.duration) {
      const minDuration = characteristics.duration * 0.9;
      const maxDuration = characteristics.duration * 1.1;
      query.duration = { $gte: minDuration, $lte: maxDuration };
    }

    return GeneratedMusic.find(query).sort({ usageCount: -1, createdAt: -1 }).limit(limit);
  }

  /**
   * Increment usage count when music is reused
   */
  async incrementUsageCount(id: string): Promise<IGeneratedMusic | null> {
    return GeneratedMusic.findByIdAndUpdate(id, { $inc: { usageCount: 1 } }, { new: true });
  }

  /**
   * Get user's most used music
   */
  async getMostUsedByUser(userId: string, limit: number = 10): Promise<IGeneratedMusic[]> {
    return GeneratedMusic.find({ userId }).sort({ usageCount: -1, createdAt: -1 }).limit(limit);
  }

  /**
   * Delete music by ID
   */
  async deleteById(id: string): Promise<void> {
    await GeneratedMusic.findByIdAndDelete(id);
  }

  /**
   * Delete all music for a user
   */
  async deleteByUserId(userId: string): Promise<void> {
    await GeneratedMusic.deleteMany({ userId });
  }

  /**
   * Count total music generated by user
   */
  async countByUserId(userId: string): Promise<number> {
    return GeneratedMusic.countDocuments({ userId });
  }

  /**
   * Get user's music generation statistics
   */
  async getUserMusicStats(userId: string): Promise<{
    totalGenerated: number;
    totalUsage: number;
    mostUsedMood?: string;
    mostUsedVideoType?: string;
  }> {
    const [stats] = await GeneratedMusic.aggregate([
      { $match: { userId } },
      {
        $group: {
          _id: null,
          totalGenerated: { $sum: 1 },
          totalUsage: { $sum: '$usageCount' },
          moods: { $push: '$estimatedMood' },
          videoTypes: { $push: '$videoType' }
        }
      }
    ]);

    if (!stats) {
      return { totalGenerated: 0, totalUsage: 0 };
    }

    // Find most common mood and video type
    const moodCounts = stats.moods.filter(Boolean).reduce((acc: any, mood: string) => {
      acc[mood] = (acc[mood] || 0) + 1;
      return acc;
    }, {});

    const videoTypeCounts = stats.videoTypes.filter(Boolean).reduce((acc: any, type: string) => {
      acc[type] = (acc[type] || 0) + 1;
      return acc;
    }, {});

    const mostUsedMood =
      Object.keys(moodCounts).length > 0
        ? Object.keys(moodCounts).reduce((a, b) => (moodCounts[a] > moodCounts[b] ? a : b))
        : undefined;

    const mostUsedVideoType =
      Object.keys(videoTypeCounts).length > 0
        ? Object.keys(videoTypeCounts).reduce((a, b) => (videoTypeCounts[a] > videoTypeCounts[b] ? a : b))
        : undefined;

    return {
      totalGenerated: stats.totalGenerated,
      totalUsage: stats.totalUsage,
      mostUsedMood,
      mostUsedVideoType
    };
  }
}

export default new GeneratedMusicRepository();
